name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            libgles2-mesa-dev \
            libsdl2-dev \
            libjpeg-dev \
            libstorm-dev

      - name: build
        run: cmake -B build && cmake --build build

      # - name: test
      #   run: make check

      # - name: distcheck
      #   run: make distcheck
